# Generated by Django 5.2.8 on 2025-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('web site', 'Web Site'), ('web dasturlash', 'Web Dasturlash'), ('mobil va desctop ilovalar', 'Mobil Va Desctop Ilovalar'), ('telegram bot', 'Telegram Bot')], max_length=50, null=True)),
                ('status_led', models.CharField(choices=[('new led', 'New Led'), ('later', 'Later'), ('failed', 'Failed')], default='new led', max_length=50)),
                ('call_time', models.CharField(choices=[('09-12', 'Ertalab 9 dan 12 gacha'), ('12-15', '12 dan 15 gacha'), ('15-18', '15 dan 18 gacha'), ('18-21', '18 dan 21 gacha'), ('any', 'Istalgan vaqtda')], default='any', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ('-created_at',),
            },
        ),
    ]
