# Generated by Django 5.2.8 on 2025-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_day_contacts_deleted_at_contacts_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='month',
            field=models.CharField(blank=True, choices=[('yanvar', 'Yanvar'), ('fevtal', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'Iyun'), ('iyul', 'Iyul'), ('avgust', 'Avgust'), ('sentabr', 'Sentabr'), ('oktabr', 'Oktabr'), ('noyabr', 'Noyabr'), ('dekabr', 'Dekabr')], max_length=10, null=True),
        ),
    ]
