# Generated by Django 5.2.8 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='month',
            field=models.CharField(blank=True, choices=[('01', 'Yanvar'), ('02', 'Fevral'), ('03', 'Mart'), ('04', 'Aprel'), ('05', 'May'), ('06', 'Iyun'), ('07', 'Iyul'), ('08', 'Avgust'), ('09', 'Sentabr'), ('10', 'Oktabr'), ('11', 'Noyabr'), ('12', 'Dekabr')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='call_time',
            field=models.CharField(choices=[('09:00-12:00', '09-12'), ('12:00-15:00', '12-15'), ('15:00-18:00', '15-18'), ('18:00-21:00', '18-21'), ('Istalgan vaqtda', 'anytime')], default='Istalgan vaqtda', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
