# Generated by Django 5.2.8 on 2025-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_status_led'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='status_led',
            field=models.CharField(choices=[('new_led', 'New Led'), ('later', 'Later'), ('failed', 'Failed'), ('success', 'Success')], default='new_led', max_length=50),
        ),
    ]
