# Generated by Django 5.2.8 on 2026-01-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contacts_status_led'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='operator_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram orqali'), ('google', 'Google orqali'), ('friends', 'Tanishlar orqali'), ('telegram', 'Telegram orqali')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='call_time',
            field=models.CharField(choices=[('09:00-12:00', '09-12'), ('12:00-15:00', '12-15'), ('15:00-18:00', '15-18'), ('18:00-21:00', '18-21'), ('anytime', "Istalgan vaqtda qo'ng'itoq qilish mumkin")], default='anytime', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('website', 'Website'), ('landing_page', 'Landing_Page'), ('mobile_app', 'Mobile_App'), ('telegram_bot', 'Telegram_Bot')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='status_led',
            field=models.CharField(choices=[('new_led', 'Yangi Lead'), ('later', "Keyintoq bog'lanish uchun lead"), ('failed', 'Bizning hizmatlarimiz kerak emas'), ('success', 'Bizning hizmatlarimizdan foydalanadi')], default='new_led', max_length=50),
        ),
    ]
