# Generated by Django 5.2.8 on 2026-01-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_operator_comment_contacts_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='call_time',
            field=models.CharField(choices=[('09:00-12:00', '09:00-12:00'), ('12:00-15:00', '12:00-15:00'), ('15:00-18:00', '15:00-18:00'), ('18:00-21:00', '18:00-21:00'), ('anytime', 'Call Anytime')], default='anytime', max_length=50, verbose_name='Call Time'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='month',
            field=models.CharField(blank=True, choices=[('yanvar', 'January'), ('fevral', 'February'), ('mart', 'March'), ('aprel', 'April'), ('may', 'May'), ('iyun', 'June'), ('iyul', 'July'), ('avgust', 'August'), ('sentabr', 'September'), ('oktabr', 'October'), ('noyabr', 'November'), ('dekabr', 'December')], max_length=10, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='operator_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Operator Comment'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('website', 'Website'), ('landing_page', 'Landing Page'), ('mobile_app', 'Mobile Application'), ('erp_system', 'ERP System'), ('telegram_bot', 'Telegram Bot'), ('support_bot', 'Support Bot')], max_length=50, null=True, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Via Instagram'), ('google', 'Via Google'), ('friends', 'Via Friends'), ('telegram', 'Via Telegram')], max_length=20, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='status_led',
            field=models.CharField(choices=[('new_led', 'New Lead'), ('later', 'Call Back Later'), ('failed', 'Service Not Needed'), ('success', 'Using Our Services')], default='new_led', max_length=50, verbose_name='Lead Status'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='User Comment'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
