# Generated by Django 5.2.8 on 2026-01-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_options_alter_contacts_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='call_time',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='day',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='month',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='year',
        ),
    ]
